# Generated by Django 5.0.3 on 2024-03-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generated')},
        ),
    ]
